In [3]:
import numpy as np
import time as t

size = 10
list1 = range(size)
list2 = range(size)
start = t.time()
result = [x+y for x,y in zip(list1,list2)] # zip() is used to pair items from two or more lists together, position by position.
                                           # list1 = [1, 2, 3]
                                           # list2 = [4, 5, 6]
                                           # → zip gives: (1,4), (2,5), (3,6)
                                           # List Comprehension
end = t.time()
print("total time taken by list", end - start)

arr1 = np.arange(size)
arr2 = np.arange(size)
start = t.time()
result = arr1 + arr2
end = t.time()
print("total time taken by array", end - start)

total time taken by list 0.0
total time taken by array 0.0


In [3]:
# array time
%timeit np.arange(1,90)**2

4.06 μs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
# list time
%timeit [j**2 for j in range(1,90)]

11.5 μs ± 1.4 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
                                                 # 30-10-2025  by vikas sir 

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [43]:
a = np.array([1,2,'abs',4,5])
print(a)

['1' '2' 'abs' '4' '5']


In [44]:
a[1] = 111
print(a)

['1' '111' 'abs' '4' '5']


In [41]:
b =[1,2,'absd',4,5]
c = np.array(b)
print(c)
c.dtype

['1' '2' 'absd' '4' '5']


dtype('<U21')

In [42]:
c[1] = 98
print(c)

['1' '98' 'absd' '4' '5']


In [36]:
b = np.array((1,9,4,5,7))
print(b)

[1 9 4 5 7]


In [29]:
b.shape

(5,)

In [26]:
b.ndim

1

In [37]:
b.dtype

dtype('int64')

In [47]:
import sys
a = 1
print(sys.getsizeof(a))

28


In [15]:
b = "abc"
print(sys.getsizeof(b))

44


In [19]:
c = 13.14
print(sys.getsizeof(c))

24


In [48]:
c = [1,2,3,4,5,6]
print(sys.getsizeof(c))

104


In [ ]:
                                                                # 31-10-2025

In [49]:
print(c)

[1, 2, 3, 4, 5, 6]


In [53]:
# without indexing loop
for i in c:
    if i % 2 == 0:
        print(i+2)

4
6
8


In [58]:
# with indexing loop

for i in range(len(c)):
    c[i] = c[i] + 2
    print(c[i])


3
4
5
6
7
8


In [13]:
# adding a null value to list

a = [1,2,3,None,4,5]
print(a)


[1, 2, 3, None, 4, 5]


In [9]:
# adding a null value to array

b = np.array([2,4,6,8,np.nan,9,5])
print(b)
print(b.dtype)

[ 2.  4.  6.  8. nan  9.  5.]
float64


In [7]:
type(np.nan)

float

In [11]:
c = np.array([2,2,1,8,None,9,5])
print(c)
print(c.dtype)

[2 2 1 8 None 9 5]
object


In [19]:
# passing dict in array

d = {'name':['T','S','A'],'age':[12,23,34]}
e = np.array(d)
print(e)

{'name': ['T', 'S', 'A'], 'age': [12, 23, 34]}


In [1]:
                                                    # 01-11-2025

In [5]:
# 2D reshape

a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# 3D reshape

a = np.array([1,2,3,4,5,6]).reshape(3,2,1)   # reshape(template,row,col)
a

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [1]:
# 4D 
import numpy as np

In [1]:
                                          # 03-11-2025

In [7]:
# problem
x = np.array([[1,3,5,6,7,8]])

for i in x:
    for j in i:
        print(j)

1
3
5
6
7
8


In [8]:
# solution
# nditer make ease to access element of array dimention do not need to write many loops
for i in np.nditer(x):
    print(i)

1
3
5
6
7
8


In [17]:
# tells indexing with nditer
#ndenumerate
x = np.array([[1,3,5,6,7,8]])
for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0) 1
(0, 1) 3
(0, 2) 5
(0, 3) 6
(0, 4) 7
(0, 5) 8


In [10]:
x = np.array([[[1,3,5,6,7,8]]])

for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 3
(0, 0, 2) 5
(0, 0, 3) 6
(0, 0, 4) 7
(0, 0, 5) 8


In [16]:
p= np.empty((2,2))
p

array([[2.12199579e-314, 1.23287955e-311],
       [6.34380289e-321, 1.23287955e-311]])

In [19]:
g = np.empty((4,4),dtype=int)
g

array([[3801155, 5570652, 6619251, 7536754],
       [4718684, 6029392, 7340097, 4456560],
       [7602273, 6029409, 7274572, 6357091],
       [6029420, 6619220, 7340141,       0]])

In [24]:
h = np.ones((7,7))
h

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
k = np.zeros((4,4))
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
                                                  # 04-10-2025

In [4]:
# arange(start,stop-1,step size 1)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# random.rand

import numpy as np
b = np.random.rand(3)
b

array([0.24919219, 0.83447839, 0.91921323])

In [4]:
# random.randint

c = np.random.randint(4)
c

0

In [5]:
c1 = np.random.randint(1,5,6)
c1

array([2, 3, 2, 1, 1, 3])

In [8]:
d = np.linspace(4,9,4)
d

array([4.        , 5.66666667, 7.33333333, 9.        ])

In [9]:
# flatten used o chane the dimention of array 2d to 1d

n =np.array([[2,3],[4,6],[5,6]])
d = n.flatten()
print(d)
d[1]=600
print(d)
print(n)     # see the original values do not get change even i assign a new value above

[2 3 4 6 5 6]
[  2 600   4   6   5   6]
[[2 3]
 [4 6]
 [5 6]]


In [17]:
# # ravel used o chane the dimention of array 2d to 1d

k = np.array([[2,3],[4,6],[7,8]])
k
h = k.ravel()
print(h)
h[1] = 390
print(h)
print(k)    # see the original values get changed when i assign a new value above

[2 3 4 6 7 8]
[  2 390   4   6   7   8]
[[  2 390]
 [  4   6]
 [  7   8]]


In [ ]:
                                                    # 05-11-2025

In [8]:
# split

a = np.array(['R-no','sname','a-id','fname'])
a


s = np.split(a,2)
s
# dividing the s table
t1 = s[0]
t2 = s[1]
print(t1)
print(t2)

['R-no' 'sname']
['a-id' 'fname']


In [10]:
#array_split

a = np.array([1,2,3,4,5,6,7])

s = np.array_split(a,8)
s

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([], dtype=int32)]

In [6]:
# sort

b = np.array([34,78,23,67,24,89,1,0,5,3,2])
np.sort(b)


array([ 0,  1,  2,  3,  5, 23, 24, 34, 67, 78, 89])

In [7]:
# concatenate

z = np.array([1,5,7,9,0])
x = np.array([3,5,6,8,12])

np.concatenate([z,x])

array([ 1,  5,  7,  9,  0,  3,  5,  6,  8, 12])

In [ ]:
                                             # 06-11-2025

In [3]:
# Transpose
import numpy as np
a = np.array([[1,2,5,7],[3,4,6,8],[9,8,7,6]])
a
print()
t = a.T
t

array([[1, 3, 9],
       [2, 4, 8],
       [5, 6, 7],
       [7, 8, 6]])

In [4]:
b = np.transpose([[1,7],[3,8],[9,6],[78,90]])
b

array([[ 1,  3,  9, 78],
       [ 7,  8,  6, 90]])

In [6]:
# Conditional based function

# where

a = np.array([2,34,5,6,8,9,-3,-1,-6,-4,55,64,-4,78,-9])
np.where(a>50)

(array([10, 11, 13], dtype=int64),)

In [7]:
np.where(a<0,0,a)

array([ 2, 34,  5,  6,  8,  9,  0,  0,  0,  0, 55, 64,  0, 78,  0])

In [14]:
np.where(a>10 & a<50)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
np.where((a>1) & (a<50))

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [16]:
# mathematicals and statisticals functions

#add

a = np.array([2,4,6,8,9])

np.add(a,3)

array([ 5,  7,  9, 11, 12])

In [ ]:
more to do

In [ ]:
                                        # 07-11-2025

In [ ]:
save

In [ ]:
load

In [2]:
f = np.array([[1,2,3],[4,5,6]])
np.savetxt("student.txt",f)

In [7]:
# using delimeter and format (%d for integer and f for decimal)

f = np.array([[1,2,3],[4,5,6]])
np.savetxt("studentdel.txt",f,delimiter=',',fmt='%0.2f') # float
                                                        # integer

# try in integer

In [9]:
# using header and footer with comments(Bydefault comment is #)

f = np.array([[1,2,3],[4,5,6]])
np.savetxt("studentdelcomm.txt",f,delimiter=',',fmt='%d',header='start',footer='end',comments="$") 


# Task given by sir

In [7]:
a = np.ones((5,5),dtype = int)
a
print()
a[1:-1,1:-1] = 0
print(a)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [4]:
a =[2,3,0,1,0,9]
aa =np.array(a)
np.where(aa!=0)

(array([0, 1, 3, 5], dtype=int64),)

In [4]:
a = np.zeros(10,dtype='int')
a
a[4] = 9
print(a)

[0 0 0 0 9 0 0 0 0 0]


In [59]:
np.ones((3,3),dtype = 'bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# e = np.random.randint(1,12,16).reshape((4,4))
print(e)
print()
print("First row =",e[0:1,:])
print("Last col =",e[:,3:4])


[[ 4  7  2  8]
 [11 10  3  1]
 [ 8  1  5  1]
 [ 1 10  1  1]]

First row = [[4 7 2 8]]
Last col = [[8]
 [1]
 [1]
 [1]]


In [3]:
a = np.array([12,45,67,89,90])
b = np.array([12,56,67,45,90])
np.where(a==b)

(array([0, 2, 4], dtype=int64),)

In [60]:
e = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(e)
g = np.sort(e[:,1:2])
g
# np.where(e[:,1:2],np.sort(e),e)
  kk          

IndentationError: unexpected indent (725050046.py, line 6)

In [2]:
a = np.array([1,3,5,7,6,9,23,5,22,66,88,45,78,12,67])
np.where(a%2 != 0,-1,a)

array([-1, -1, -1, -1,  6, -1, -1, -1, 22, 66, 88, -1, 78, 12, -1])