In [1]:
import numpy as np
import time as t

size = 10
list1 = range(size)
list2 = range(size)
start = t.time()
result = [x+y for x,y in zip(list1,list2)] # zip() is used to pair items from two or more lists together, position by position.
                                           # list1 = [1, 2, 3]
                                           # list2 = [4, 5, 6]
                                           # → zip gives: (1,4), (2,5), (3,6)
                                           # List Comprehension
end = t.time()
print("total time taken by list", end - start)

arr1 = np.arange(size)
arr2 = np.arange(size)
start = t.time()
result = arr1 + arr2
end = t.time()
print("total time taken by array", end - start)

total time taken by list 0.0
total time taken by array 0.0


In [3]:
# array time
%timeit np.arange(1,90)**2

4.06 μs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
# list time
%timeit [j**2 for j in range(1,90)]

11.5 μs ± 1.4 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [1]:
                                                 # 30-10-2025  by vikas sir 

In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [43]:
a = np.array([1,2,'abs',4,5])
print(a)

['1' '2' 'abs' '4' '5']


In [44]:
a[1] = 111
print(a)

['1' '111' 'abs' '4' '5']


In [41]:
b =[1,2,'absd',4,5]
c = np.array(b)
print(c)
c.dtype

['1' '2' 'absd' '4' '5']


dtype('<U21')

In [42]:
c[1] = 98
print(c)

['1' '98' 'absd' '4' '5']


In [3]:
b = np.array((1,9,4,5,7))
print(b)

[1 9 4 5 7]


In [4]:
b.shape

(5,)

In [26]:
b.ndim

1

In [37]:
b.dtype

dtype('int64')

In [47]:
import sys
a = 1
print(sys.getsizeof(a))

28


In [15]:
b = "abc"
print(sys.getsizeof(b))

44


In [19]:
c = 13.14
print(sys.getsizeof(c))

24


In [48]:
c = [1,2,3,4,5,6]
print(sys.getsizeof(c))

104


In [ ]:
                                                                # 31-10-2025

In [49]:
print(c)

[1, 2, 3, 4, 5, 6]


In [53]:
# without indexing loop
for i in c:
    if i % 2 == 0:
        print(i+2)

4
6
8


In [58]:
# with indexing loop

for i in range(len(c)):
    c[i] = c[i] + 2
    print(c[i])


3
4
5
6
7
8


In [13]:
# adding a null value to list

a = [1,2,3,None,4,5]
print(a)


[1, 2, 3, None, 4, 5]


In [9]:
# adding a null value to array

b = np.array([2,4,6,8,np.nan,9,5])
print(b)
print(b.dtype)

[ 2.  4.  6.  8. nan  9.  5.]
float64


In [7]:
type(np.nan)

float

In [11]:
c = np.array([2,2,1,8,None,9,5])
print(c)
print(c.dtype)

[2 2 1 8 None 9 5]
object


In [19]:
# passing dict in array

d = {'name':['T','S','A'],'age':[12,23,34]}
e = np.array(d)
print(e)

{'name': ['T', 'S', 'A'], 'age': [12, 23, 34]}


In [1]:
                                                    # 01-11-2025

In [7]:
# 2D reshape

a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 3D reshape

a = np.array([1,2,3,4,5,6]).reshape(3,2,1)   # reshape(template,row,col)
a

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [1]:
# 4D 
import numpy as np

In [1]:
                                          # 03-11-2025

In [7]:
# problem
x = np.array([[1,3,5,6,7,8]])

for i in x:
    for j in i:
        print(j)

1
3
5
6
7
8


In [8]:
# solution
# nditer make ease to access element of array dimention do not need to write many loops
for i in np.nditer(x):
    print(i)

1
3
5
6
7
8


In [17]:
# tells indexing with nditer
#ndenumerate
x = np.array([[1,3,5,6,7,8]])
for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0) 1
(0, 1) 3
(0, 2) 5
(0, 3) 6
(0, 4) 7
(0, 5) 8


In [10]:
x = np.array([[[1,3,5,6,7,8]]])

for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 3
(0, 0, 2) 5
(0, 0, 3) 6
(0, 0, 4) 7
(0, 0, 5) 8


In [16]:
p= np.empty((2,2))
p

array([[2.12199579e-314, 1.23287955e-311],
       [6.34380289e-321, 1.23287955e-311]])

In [19]:
g = np.empty((4,4),dtype=int)
g

array([[3801155, 5570652, 6619251, 7536754],
       [4718684, 6029392, 7340097, 4456560],
       [7602273, 6029409, 7274572, 6357091],
       [6029420, 6619220, 7340141,       0]])

In [24]:
h = np.ones((7,7))
h

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
k = np.zeros((4,4))
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
                                                  # 04-10-2025

In [9]:
# arange(start,stop-1,step size 1)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# random.rand

import numpy as np
b = np.random.rand(3)
b

array([0.24919219, 0.83447839, 0.91921323])

In [4]:
# random.randint

c = np.random.randint(4)
c

0

In [12]:
c1 = np.random.randint(1,500,100)
c1

array([494,  97, 485, 377, 353, 381, 471, 486, 363, 252, 486, 218, 148,
       186, 382,  84,  20, 311, 189, 137, 206, 155, 401, 228, 131, 221,
       316, 102, 419, 403, 496,  64,  11, 297, 395, 223, 305, 448, 382,
       485, 255, 451,  88, 411,  65,  11, 100, 237,  23, 428, 133, 477,
       363, 398,  13, 253, 399, 350, 214, 265, 421, 339, 411, 173,  69,
       143, 197, 202, 383,  99, 323,  41, 136,  42, 352, 284, 144, 400,
       145, 457,  47,  28, 176, 269, 338,  69, 131, 376, 442, 178, 472,
       319, 358, 259, 499, 224, 257, 112, 327, 127])

In [8]:
d = np.linspace(4,9,4)
d

array([4.        , 5.66666667, 7.33333333, 9.        ])

In [9]:
# flatten used to change the dimention of array 2d to 1d

n =np.array([[2,3],[4,6],[5,6]])
d = n.flatten()
print(d)
d[1]=600
print(d)
print(n)     # see the original values do not get change even i assign a new value above

[2 3 4 6 5 6]
[  2 600   4   6   5   6]
[[2 3]
 [4 6]
 [5 6]]


In [13]:
# # ravel used to change the dimention of array 2d to 1d

k = np.array([[2,3],[4,6],[7,8]])
k
h = k.ravel()
print(h)
h[1] = 390
print(h)
print(k)    # see the original values get changed when i assign a new value above

[2 3 4 6 7 8]
[  2 390   4   6   7   8]
[[  2 390]
 [  4   6]
 [  7   8]]


In [ ]:
                                                    # 05-11-2025

In [15]:
# split

a = np.array(['R-no','sname','a-id','fname'])
a


s = np.split(a,2)
s
# dividing the s table
t1 = s[0]
t2 = s[1]
print(t1)
print(t2)

['R-no' 'sname']
['a-id' 'fname']


In [10]:
#array_split

a = np.array([1,2,3,4,5,6,7])

s = np.array_split(a,8)
s

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([], dtype=int32)]

In [17]:
# sort

b = np.array([34,78,23,67,24,89,1,0,5,3,2])
np.sort(b)


array([ 0,  1,  2,  3,  5, 23, 24, 34, 67, 78, 89])

In [19]:
# concatenate

z = np.array([1,5,7,9,0])
x = np.array([3,5,6,8,12])

np.concatenate([z,x])

array([ 1,  5,  7,  9,  0,  3,  5,  6,  8, 12])

In [ ]:
                                             # 06-11-2025

In [3]:
# Transpose
import numpy as np
a = np.array([[1,2,5,7],[3,4,6,8],[9,8,7,6]])
a
print()
t = a.T
t

array([[1, 3, 9],
       [2, 4, 8],
       [5, 6, 7],
       [7, 8, 6]])

In [4]:
b = np.transpose([[1,7],[3,8],[9,6],[78,90]])
b

array([[ 1,  3,  9, 78],
       [ 7,  8,  6, 90]])

In [2]:
# Conditional based function
import numpy as np
# where

a = np.array([2,34,5,6,8,9,-3,-1,-6,-4,55,64,-4,78,-9])
np.where(a>50)

(array([10, 11, 13], dtype=int64),)

In [3]:
np.where(a<0,0,a)

array([ 2, 34,  5,  6,  8,  9,  0,  0,  0,  0, 55, 64,  0, 78,  0])

In [14]:
np.where(a>10 & a<50)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
np.where((a>1) & (a<50))

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [16]:
# mathematicals and statisticals functions

#add

a = np.array([2,4,6,8,9])

np.add(a,3)

array([ 5,  7,  9, 11, 12])

In [ ]:
more to do

In [ ]:
                                        # 07-11-2025

In [ ]:
save

In [ ]:
load

In [2]:
f = np.array([[1,2,3],[4,5,6]])
np.savetxt("student.txt",f)

In [7]:
# using delimeter and format (%d for integer and f for decimal)

f = np.array([[1,2,3],[4,5,6]])
np.savetxt("studentdel.txt",f,delimiter=',',fmt='%0.2f') # float
                                                        # integer

# try in integer

In [9]:
# using header and footer with comments(Bydefault comment is #)

f = np.array([[1,2,3],[4,5,6]])
np.savetxt("studentdelcomm.txt",f,delimiter=',',fmt='%d',header='start',footer='end',comments="$") 


# Task given by sir

In [7]:
a = np.ones((5,5),dtype = int)
a
print()
a[1:-1,1:-1] = 0
print(a)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [4]:
a =[2,3,0,1,0,9]
aa =np.array(a)
np.where(aa!=0)

(array([0, 1, 3, 5], dtype=int64),)

In [4]:
a = np.zeros(10,dtype='int')
a
a[4] = 9
print(a)

[0 0 0 0 9 0 0 0 0 0]


In [59]:
np.ones((3,3),dtype = 'bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# e = np.random.randint(1,12,16).reshape((4,4))
print(e)
print()
print("First row =",e[0:1,:])
print("Last col =",e[:,3:4])


[[ 4  7  2  8]
 [11 10  3  1]
 [ 8  1  5  1]
 [ 1 10  1  1]]

First row = [[4 7 2 8]]
Last col = [[8]
 [1]
 [1]
 [1]]


In [3]:
a = np.array([12,45,67,89,90])
b = np.array([12,56,67,45,90])
np.where(a==b)

(array([0, 2, 4], dtype=int64),)

In [60]:
e = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(e)
g = np.sort(e[:,1:2])
g
# np.where(e[:,1:2],np.sort(e),e)
  kk          

IndentationError: unexpected indent (725050046.py, line 6)

In [2]:
a = np.array([1,3,5,7,6,9,23,5,22,66,88,45,78,12,67])
np.where(a%2 != 0,-1,a)

array([-1, -1, -1, -1,  6, -1, -1, -1, 22, 66, 88, -1, 78, 12, -1])

# Exercise No 1

In [ ]:
# 11-11-2025        

In [3]:
# 1D arary
n= np.array([10,20,30,40,50,60,70,80])
n

array([10, 20, 30, 40, 50, 60, 70, 80])

In [3]:
n[:4]

array([10, 20, 30, 40])

In [4]:
n[4:2]

array([], dtype=int32)

In [5]:
n[4:]

array([50, 60, 70, 80])

In [6]:
n[:4:3]

array([10, 40])

In [7]:
n[-1:]

array([80])

In [8]:
n[-4:]

array([50, 60, 70, 80])

In [11]:
n[-3:-1]

array([60, 70])

In [12]:
n[-8:]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [13]:
n[:6:2]

array([10, 30, 50])

In [14]:
n[:-6:-2]

array([80, 60, 40])

In [15]:
n[:-6:2] #------------------

array([10])

In [16]:
n[:-6:3]   #--------------------

array([10])

In [17]:
n[:-5:-1]

array([80, 70, 60, 50])

In [18]:
n[:-5:-3]

array([80, 50])

In [4]:
n[:-5:3]   #---------------------- ask sir

array([10])

In [27]:
# 2D arary
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
b[1,1:4]

array([7, 8, 9])

In [30]:
b[0:2,4]

array([ 5, 10])

In [31]:
b[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# Exercise No 1

In [ ]:
# Q1

In [33]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a[2:5]

array([2, 3, 4])

In [ ]:
# Q2

In [34]:
b = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
b[:2,:2]

array([[0, 1],
       [3, 4]])

In [ ]:
# Q3

In [35]:
c = np.array([[1,3,5,7],[9,11,13,15]])
c[:2,:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# Q4

In [36]:
d = np.array([[1,3,5,7],[9,11,13,15],[2,4,6,8]])
d[:2,:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# Q5

In [37]:
d[1:3,2:4]

array([[13, 15],
       [ 6,  8]])

In [ ]:
# Q6

In [42]:
aa = np.random.randint(1,10,16).reshape(4,4)
print(aa)
print()
print("first row =",aa[0,0:])
print("last col =",aa[0:,3])

[[1 4 9 8]
 [3 6 9 5]
 [1 5 4 1]
 [9 6 8 8]]

first row = [1 4 9 8]
last col = [8 5 1 8]


In [ ]:
# Q7

In [46]:
ab = np.random.randint(1,10,16).reshape(4,4)
print(ab)
print()
print("first 2 rows and first 2 columns :")
print(ab[0:2,0:2])      

[[1 5 7 3]
 [8 9 2 6]
 [9 2 5 2]
 [3 8 8 5]]

first 2 rows and first 2 columns :
[[1 5]
 [8 9]]


In [ ]:
# Q8

In [47]:
a = np.array([1,2,3,4,5])
b = np.array([1,4,3,7,8])
np.where(a==b)

(array([0, 2], dtype=int64),)

In [ ]:
# Q9

In [56]:
count = 0
for i in range(15):
    if 1 == 1
    

np.full(25,0+1).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
b[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [59]:
b[2:0,2:0]

array([], shape=(0, 0), dtype=int32)

In [61]:
b[2:0:-1,2:0:-1] # -------------------------

array([[10,  9],
       [ 6,  5]])

In [ ]:
# Q10

In [62]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [63]:
b[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [64]:
a[2:6:3]

array([30, 60])

In [65]:
a[-1:-3]

array([], dtype=int32)

In [68]:
b[::-1]     #-----------------------------------

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [67]:
b[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
# Q11

In [70]:
v = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
v

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Q12

In [71]:
d = np.array([10,20,30,40,50,60,70])
print(d[-4:])

[40 50 60 70]


In [ ]:
                                       # 12-11-2025

In [ ]:
# copy

In [ ]:
#  view