<!-- Main container -->
<div style="font-family: Consolas, 'Courier New', monospace; background: #1e1e1e; color: #d4d4d4; border: 1px solid #333; border-radius: 12px; padding: 25px; line-height: 1.7; max-width: 950px; margin: auto; box-shadow: 0 0 18px rgba(0,0,0,0.6);">

  <h1 style="color:#4a90e2; text-align:center; margin-bottom:25px;">✨ NumPy Library Functions </h1>

  <!-- Function Block -->
  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">1. <code style="color:#4ec9b0;">np.arange()</code></h2>
    <p><b>Syntax:</b> <code style="color:#4ec9b0;">numpy.arange(start, stop, step, dtype=None)</code></p>
    <p><b>Definition:</b> Creates arrays with evenly spaced values. Similar to Python’s <code style="color:#4ec9b0;">range()</code>, but faster and returns a NumPy array.</p>
    <div style="background:#252526; padding:12px; border-radius:8px; margin-top:10px;">
<pre style="margin:0; font-size:14px; color:#d4d4d4;">
arr1 = np.arange(5)          # [0 1 2 3 4]
arr2 = np.arange(2, 10, 2)   # [2 4 6 8]
arr3 = np.arange(0, 1, 0.2)  # [0. 0.2 0.4 0.6 0.8]
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">2. <code style="color:#4ec9b0;">np.linspace()</code></h2>
    <p><b>Definition:</b> Generates evenly spaced numbers over a range, based on the number of samples.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
arr1 = np.linspace(0, 10, 5)           # [0.  2.5  5.  7.5 10.]
arr2 = np.linspace(1, 2, 4, endpoint=False)  # [1.   1.25 1.5  1.75]
arr3 = np.linspace(0, 1, 5, retstep=True)    # (array([...]), step_size)
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">3. <code style="color:#4ec9b0;">np.random.randint()</code></h2>
    <p><b>Definition:</b> Generates random integers in a given range.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
np.random.randint(10)            # 0–9
np.random.randint(5, 15)         # 5–14
np.random.randint(1, 10, size=5) # [3 8 1 6 9]
np.random.randint(1, 10, size=(2,3)) # 2x3 matrix
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">4. <code style="color:#4ec9b0;">np.random.rand()</code></h2>
    <p><b>Definition:</b> Generates random floats between <b>0 and 1</b>.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
np.random.rand()        # 0.3748 (example)
np.random.rand(3)       # [0.12 0.87 0.45]
np.random.rand(2, 3)    # 2x3 matrix
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">5. <code style="color:#4ec9b0;">np.reshape()</code></h2>
    <p><b>Definition:</b> Changes the shape of an array without changing its data.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
arr = np.arange(6)           # [0 1 2 3 4 5]

np.reshape(arr, (2, 3))      
# [[0 1 2]
#  [3 4 5]]

arr.reshape(3, 2)            
# [[0 1]
#  [2 3]
#  [4 5]]
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">6. <code style="color:#4ec9b0;">array.shape</code></h2>
    <p><b>Definition:</b> Returns array dimensions as a tuple.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
arr1 = np.array([1, 2, 3, 4])
arr1.shape    # (4,)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape    # (2, 3)

arr3 = np.zeros((2, 3, 4))
arr3.shape    # (2, 3, 4)
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">7. <code style="color:#4ec9b0;">np.eye()</code></h2>
    <p><b>Definition:</b> Creates an identity matrix with ones on the diagonal.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
np.eye(3)          
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

np.eye(3, 4)   # 3x4 matrix
np.eye(4, k=1) # diagonal shifted up
np.eye(4, k=-1)# diagonal shifted down
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">8. <code style="color:#4ec9b0;">np.ones()</code></h2>
    <p><b>Definition:</b> Creates an array filled with ones.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
np.ones(4)           
# [1. 1. 1. 1.]

np.ones((2, 3))      
# [[1. 1. 1.]
#  [1. 1. 1.]]

np.ones((2, 3), dtype=int) 
# [[1 1 1]
#  [1 1 1]]
</pre>
    </div>
  </div>

  <div style="margin-bottom:30px;">
    <h2 style="color:#dcdcaa;">9. <code style="color:#4ec9b0;">np.zeros()</code></h2>
    <p><b>Definition:</b> Creates an array filled with zeros.</p>
    <div style="background:#252526; padding:12px; border-radius:8px;">
<pre style="margin:0; font-size:14px;">
np.zeros(5)           
# [0. 0. 0. 0. 0.]

np.zeros((2, 3))      
# [[0. 0. 0.]
#  [0. 0. 0.]]

np.zeros((3, 3), dtype=int)
# [[0 0 0]
#  [0 0 0]
#  [0 0 0]]
</pre>
    </div>
  </div>

</div>
