In [1]:
import numpy as np

In [3]:
arr = np.array([[12,1,4],[100,9,3],[2,96,76]])
print(arr)

[[ 12   1   4]
 [100   9   3]
 [  2  96  76]]


In [6]:
np.sort(arr,axis=0) # this gives the output according to coloumn

array([[  2,   1,   3],
       [ 12,   9,   4],
       [100,  96,  76]])

In [8]:
np.sort(arr,axis=1) # this gives the output according to row

array([[  1,   4,  12],
       [  3,   9, 100],
       [  2,  76,  96]])

In [11]:
arr = np.eye(3,3,dtype=str)
arr

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [32]:
a = np.array([[2,1],[3,1]])
print(a)
a.ndim

[[2 1]
 [3 1]]


2

In [33]:
b = np.array([[4,1],[5,1]])
print(b)
b.ndim

[[4 1]
 [5 1]]


2

In [35]:
print(np.dot(a,b))


[[13  3]
 [17  4]]


In [40]:
a = np.eye(2,2,dtype=int)
print(arr)

[[1 0]
 [0 1]]


In [43]:
b = np.array([[2,6],[4,2]])
print(b)

[[2 6]
 [4 2]]


In [45]:
print(np.dot(b,a))

[[2 6]
 [4 2]]
